### ISSUE TITLE
Can't edit the Email TextInput

### ISSUE THREAD

**Issue by LouisJS** [esbenp/react-native-clean-form#66] opened 2017-10-09 18:30 UTC
"prop-types": "^15.6.0",
 "react": "16.0.0-beta.5",
 "react-native": "0.49.1",
 "react-redux": "^5.0.6",
 "redux": "^3.7.2",
 "redux-form": "^7.1.0"

The [React Native - Redux Form Implementation Guide](http://esbenp.github.io/2017/01/06/react-native-redux-form-immutable-styled-components/)
**3. Connect the form fields to the store using the Field wrapper**

Following the guide, when i arrive at this step and add the 'value' property to my InputText, i can't edit it in my iOS Simulator and so my form doesn't work.

Anyone facing this issue ?

**Comment by erikras** [comment] 2017-10-09 19:06
These might be related:
- https://github.com/erikras/redux-form/pull/3460 (in `v7.1.0`)
- https://github.com/erikras/redux-form/pull/3496 (merged today, not yet released)

Confirmation that one of these is the cause or solution would be much appreciated.

**Comment by LouisJS** [comment] 2017-10-10 08:14
Unfortunately, i haven't found any issue nor solution related to mine in your links.
No error is triggered.

This is my form which is called by reduxForm

      <View style={styles.container}>
       <Text>Email:</Text>
       <Field name="email" component={renderInput} />
       <TouchableOpacity onPress={handleSubmit(submit)}>
         <Text style={styles.button}>Submit</Text>
       </TouchableOpacity>
     </View>

And this is what my component looks like


     const renderInput = ({ input: { value, onChange, onBlur, onFocus }}) => {
       return <TextInput
                     style={styles.input}
                     onChangeText={onChange}
                     onBlur={onBlur}
                     onFocus={onFocus}
                     value={value} 
                  />
    }

The `value` property _freezes_ the input and the onChangeText doesn't seems to work at all.

**Comment by jkomyno** [comment] 2017-10-10 09:19
@erikras, I don't have this issue, if necessari I can provide a gist.

@LouisJS, you don't seem to be passing the `onChange` prop to <Field />

**Comment by LouisJS** [comment] 2017-10-10 09:34
@jkomyno Hi. I'm passing the `input.onChange` method to `TextInput` with `onChangeText`.
It is such a simple case, i don't get why it doesn't work properly.

If there any chances you could provide a working example. That would help me understand my mistake.

**Comment by LouisJS** [comment] 2017-10-11 13:41
Solved.
If it ever happens to you. You might have something wrong with your Redux Store setup (very hard to debug without Redux Dev Tools working on Simulator JS debugger)
Or checkout if your react-native is not too recent. (had to downgrade to 0.46.x <=

**Closed** 2017-10-11 13:41 UTC
